main: de.ronnypianist.Main
name: Molecraft
author: RonnyPianist
version: 1.0
commands:
   heal:
      description: You can heal yourself with this Command!
   kit:
      description: You can open the Kit menu!
   setspawn:
      description: Set the Spawn!
   spawn:
      description: Go to the Spawn!
   party:
      description: Party!
   cc:
      description: Clear the Chat!